# -*- coding: utf-8 -*-
"""Create a complete fictional M2 thesis fixture for the real Word matrix.

The generated source is anonymous and disposable.  The production CLI, not
this helper, performs the assembly, field update, pagination measurement and
publication gates.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Dict

from docx import Document
from docx.opc.constants import RELATIONSHIP_TYPE as RT
from docx.opc.packuri import PackURI
from docx.opc.part import Part
from docx.oxml import OxmlElement, parse_xml
from docx.oxml.ns import nsdecls, qn
from docx.shared import Inches


def _append_simple_field(paragraph, instruction: str, cached: str = "0") -> OxmlElement:
    field = OxmlElement("w:fldSimple")
    field.set(qn("w:instr"), instruction)
    run = OxmlElement("w:r")
    text = OxmlElement("w:t")
    text.text = cached
    run.append(text)
    field.append(run)
    paragraph._p.append(field)
    return field


def _append_bookmarked_field(paragraph, name: str, instruction: str, cached: str = "0", bookmark_id: int = 900) -> None:
    start = OxmlElement("w:bookmarkStart")
    start.set(qn("w:id"), str(bookmark_id))
    start.set(qn("w:name"), name)
    paragraph._p.append(start)
    _append_simple_field(paragraph, instruction, cached)
    end = OxmlElement("w:bookmarkEnd")
    end.set(qn("w:id"), str(bookmark_id))
    paragraph._p.append(end)


def _add_footnotes(doc: Document) -> None:
    xml = f"""<w:footnotes {nsdecls('w')}>
      <w:footnote w:type="separator" w:id="-1"><w:p><w:r><w:separator/></w:r></w:p></w:footnote>
      <w:footnote w:type="continuationSeparator" w:id="0"><w:p><w:r><w:continuationSeparator/></w:r></w:p></w:footnote>
      <w:footnote w:id="1"><w:p><w:r><w:footnoteRef/><w:t>匿名论文第一条虚构脚注。</w:t></w:r></w:p></w:footnote>
    </w:footnotes>"""
    part = Part(
        PackURI("/word/footnotes.xml"),
        "application/vnd.openxmlformats-officedocument.wordprocessingml.footnotes+xml",
        xml.encode("utf-8"),
        doc.part.package,
    )
    doc.part.relate_to(part, RT.FOOTNOTES)


def _add_endnotes(doc: Document) -> None:
    xml = f"""<w:endnotes {nsdecls('w')}>
      <w:endnote w:type="separator" w:id="-1"><w:p><w:r><w:separator/></w:r></w:p></w:endnote>
      <w:endnote w:type="continuationSeparator" w:id="0"><w:p><w:r><w:continuationSeparator/></w:r></w:p></w:endnote>
      <w:endnote w:id="1"><w:p><w:r><w:endnoteRef/><w:t>匿名论文第一条虚构尾注。</w:t></w:r></w:p></w:endnote>
    </w:endnotes>"""
    part = Part(
        PackURI("/word/endnotes.xml"),
        "application/vnd.openxmlformats-officedocument.wordprocessingml.endnotes+xml",
        xml.encode("utf-8"),
        doc.part.package,
    )
    doc.part.relate_to(part, RT.ENDNOTES)


def _add_fictional_section_text(doc: Document, title: str, paragraphs: int = 4) -> None:
    """Keep short front-matter sections from becoming false orphan pages."""
    doc.add_heading(title, level=1)
    text = (
        "这是仅用于自动化验收的虚构匿名材料，不代表任何真实个人、机构或业务内容。"
        "本段用于验证学位论文前置部分的段落组织、页眉页脚、目录关系和分页稳定性。"
        "文中结论、数据、方法与表述均为合成内容，仅服务于可重复的格式化测试。"
    )
    for index in range(paragraphs):
        doc.add_paragraph(f"{text} 本节测试段落 {index + 1}。" * 2)


def create_fixture(root: Path) -> Dict[str, str]:
    root = Path(root).resolve()
    root.mkdir(parents=True, exist_ok=True)
    source_dir = root / "source"
    source_dir.mkdir(parents=True, exist_ok=True)
    source = source_dir / "thesis-source.docx"
    doc = Document()

    # The body deliberately contains the major anonymous thesis components;
    # cover and TOC are generated by the production manifest.
    for text in ("声明", "中文摘要", "Abstract"):
        _add_fictional_section_text(doc, text)

    doc.add_heading("第一章 绪论与研究背景", level=1)
    for _ in range(4):
        doc.add_paragraph("第一章正文段落用于验证稳定的样式应用、分页测量和内容完整性门禁。" * 2)
    caption = doc.add_paragraph("图 ")
    _append_bookmarked_field(caption, "fig_caption", r"SEQ Figure \* ARABIC", "0", bookmark_id=901)
    caption.add_run(" 匿名实验流程图；交叉引用 ")
    _append_simple_field(caption, "REF fig_caption", "0")
    doc.add_paragraph("实验图片占位对象：")
    image = doc.add_picture(str(_make_image(root / "figure.png")), width=Inches(2.2))
    image._inline.docPr.set("descr", "fictional thesis image")
    table = doc.add_table(rows=2, cols=2)
    table.style = "Table Grid"
    table.cell(0, 0).text = "指标"
    table.cell(0, 1).text = "结果"
    table.cell(1, 0).text = "匿名样例"
    table.cell(1, 1).text = "通过"
    for n in range(2):
        doc.add_paragraph(f"第一章列表项目 {n + 1}", style="List Bullet")
    note = doc.add_paragraph("第一章包含脚注与尾注引用")
    note.runs[0]._r.append(parse_xml(f'<w:footnoteReference {nsdecls("w")} w:id="1"/>'))
    note.runs[0]._r.append(parse_xml(f'<w:endnoteReference {nsdecls("w")} w:id="1"/>'))

    doc.add_heading("第二章 算法设计与实验评估", level=1)
    for _ in range(5):
        doc.add_paragraph("第二章正文段落用于验证章节切换、目录链接、题注序号和 OMML 关系保留。" * 2)
    caption2 = doc.add_paragraph("表 ")
    _append_simple_field(caption2, r"SEQ Table \* ARABIC", "0")
    caption2.add_run(" 匿名性能基准表")
    math = doc.add_paragraph("损失函数：")
    math._p.append(parse_xml(f'''<m:oMath {nsdecls("m")}><m:r><m:t>L = -Σ y log(p)</m:t></m:r></m:oMath>'''))

    doc.add_heading("参考文献", level=1)
    for index in range(1, 5):
        doc.add_paragraph(
            f"[{index}] 匿名作者。虚构研究材料。用于验证参考文献页的段落完整性、样式继承与分页稳定性。"
        )
    doc.add_heading("附录 A 匿名数据说明", level=1)
    for index in range(3):
        doc.add_paragraph(
            f"附录内容仅用于验证交付范围、目录和最终 PDF 证据。测试说明 {index + 1} 保持虚构、匿名且可重复。"
        )
    _add_footnotes(doc)
    _add_endnotes(doc)
    doc.save(str(source))

    # RoleMapper derives deterministic heading bookmarks from their paths;
    # use the second chapter's generated name for a production PAGEREF field.
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
    from lib.role_mapper import RoleMapper

    assignments, _ = RoleMapper().map_document(source)
    chapter_two = [a for a in assignments if a.title_text == "第二章 算法设计与实验评估"][0]
    doc = Document(str(source))
    p = doc.add_paragraph("第二章起始页码：")
    _append_simple_field(p, f"PAGEREF {chapter_two.bookmark_name}", "1")
    doc.save(str(source))

    manifest = root / "manifest.json"
    manifest_data: Dict[str, Any] = {
        "schema_version": 3,
        "project_name": "Anonymous Complete Thesis",
        "source": {"strategy": "docx_document", "file": "source/" + source.name},
        "format": {"ref": "preset:academic-basic@1.0.0"},
        "formatting": {"mode": "restyle"},
        "layout": {
            "page_sequences": {
                "front": {"format": "lowerRoman", "restart": True, "start": 1},
                "main": {"format": "decimal", "restart": True, "start": 1},
            },
            "parts": {
                "cover": {"kind": "cover", "include_in_toc": False},
                "toc": {"kind": "generated_toc", "page_sequence": "front", "include_in_toc": False},
                "body": {"kind": "content", "page_sequence": "main", "section_type": "oddPage", "include_in_toc": True},
            },
        },
        "cover": {"main_title": "匿名学位论文样例", "sub_title": "真实 Word 验收材料", "author": "匿名", "date": "2026"},
        "output": {"documents": [{"id": "main", "filename": "thesis-complete.docx", "parts": ["cover", "toc", "body"], "toc": {"links": "internal"}}]},
    }
    manifest.write_text(json.dumps(manifest_data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return {"source": str(source), "manifest": str(manifest), "target": str(root / "thesis-complete.docx")}


def _make_image(path: Path) -> Path:
    from PIL import Image, ImageDraw

    image = Image.new("RGB", (420, 240), "white")
    draw = ImageDraw.Draw(image)
    draw.rectangle((20, 20, 400, 220), outline="black", width=3)
    draw.text((120, 105), "FICTIONAL", fill="black")
    image.save(path)
    return path


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit("usage: python3 create_complete_thesis_fixture.py OUTPUT_DIRECTORY")
    print(json.dumps(create_fixture(Path(sys.argv[1])), ensure_ascii=False, indent=2))
